### ISSUE TITLE
Our CIB's current_concurrent_checks are wrong

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#7416]
## Describe the bug

Our metric `current_concurrent_checks` from `/v1/status/CIB` has nothing to do with the actual amount of currently running checks.

## To Reproduce

1. Setup a fresh Debian 9 VM w/ 12 cores and 32GB RAM
2. Apply my Ansible playbook (see below)
3. Poll `/v1/status/CIB` and count the sleep processes every second
4. Compare

## Expected behavior

Obvious.

## Additional context

ref/NC/628417

```yaml
---
- hosts: vm
  become: yes
  become_method: sudo
  tasks:
  - name: Debian backports
    apt_repository:
      repo: >
        deb http://deb.debian.org/debian
        {{ ansible_lsb.codename }}-backports main
  - name: Icinga repo key
    apt_key:
      url: https://packages.icinga.com/icinga.key
  - name: Icinga repo
    apt_repository:
      repo: |
        deb http://packages.icinga.com/debian icinga-{{ ansible_lsb.codename }}-snapshots main
        deb-src http://packages.icinga.com/debian icinga-{{ ansible_lsb.codename }}-snapshots main
  - name: Icinga and deps
    loop:
    - icinga2
    - monitoring-plugins
    - bsd-mailx
    apt:
      name: '{{ item }}'
  - name: Icinga API
    shell: icinga2 api setup
    args:
      creates: /var/lib/icinga2/certs/ca.crt
    notify:
    - Restart Icinga
  - name: /etc/systemd/system/icinga2.service.d/limits.conf
    copy:
      dest: /etc/systemd/system/icinga2.service.d/limits.conf
      owner: root
      group: root
      mode: '0644'
      content: |
        [Service]
        TasksMax=infinity
        LimitNPROC=500000
        LimitNOFILE=500000
    notify:
    - Reload systemd
    - Restart Icinga
  - name: /etc/default/icinga2
    copy:
      dest: /etc/default/icinga2
      owner: root
      group: root
      mode: '0644'
      content: |
        ICINGA2_RLIMIT_FILES=500000
        ICINGA2_RLIMIT_PROCESSES=500000
    notify:
    - Restart Icinga
  - name: /etc/icinga2/features-available/checker.conf
    copy:
      dest: /etc/icinga2/features-available/checker.conf
      owner: root
      group: root
      mode: '0644'
      content: |
        object CheckerComponent "checker" {
          concurrent_checks = 40000
        }
    notify:
    - Restart Icinga
  - name: /etc/icinga2/conf.d/628417.conf
    copy:
      dest: /etc/icinga2/conf.d/628417.conf
      owner: root
      group: root
      mode: '0644'
      content: |
        const MaxConcurrentChecks = 40000
        object CheckCommand "mysleep" {
          command = [ "sleep", "30" ]
          timeout = 20s
        }
        for (var i in range(30000)) {
          object Host string(i) {
            check_command = "mysleep"
            check_interval = 1s // * Math.random()
          }
        }
    notify:
    - Restart Icinga
  handlers:
  - name: Reload systemd
    shell: systemctl daemon-reload
  - name: Restart Icinga
    service:
      name: icinga2
      state: restarted
```
