### ISSUE TITLE
Cannot remove-downtime using the API

### ISSUE THREAD

**Issue by iqfx** [Icinga/icinga2#8181]
## Describe the bug
I'm trying to remove downtime using the icinga2 api. I'm using the latest version of ansible to do this and worked fine before I updated to 2.12.x.

## To Reproduce

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include configuration, logs, etc. to reproduce, if relevant.

1. Make an ansible task that calls the remove-downtime functionality from the api with proper credentials
2. I used this this body: '{"filter": "host.name==\"{{ ansible_nodename }}\"", "pretty": true, "type": "Downtime", "author": "Ansible"}'
3. Use body format json
4. Get this error?
`msg": "Status code was 500 and not [200]: HTTP Error 500: Internal Server Error", "redirected": false, "server": "Icinga/2.12.0-1", "status": 500, "url": "https://icingahostname:correctport/v1/actions/remove-downtime"}`
Then in Icinga: 
```
[2020-08-18 19:13:15 +0200] information/HttpServerConnection: Request: POST /v1/actions/remove-downtime (from [someip]:43058), user: <unauthenticated>, agent: ansible-httpget).
[2020-08-18 19:13:15 +0200] warning/HttpServerConnection: Unauthorized request: POST /v1/actions/remove-downtime
```

## Expected behavior
I expect a 200 response and I can see the downtime being removed in icingaweb2.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): 2.12.0-1
* Operating System and version: CentOS 6.10
* Enabled features (`icinga2 feature list`):

```
Disabled features: compatlog elasticsearch gelf graphite icingadb influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command debuglog ido-mysql mainlog notification
```

* Icinga Web 2 version and modules (System - About): 2.7.4
* Config validation (`icinga2 daemon -C`):
Icinga in and of itself runs fine. Just some warnings about rules not being used.

## Additional context

The API user is there and works fine. I have tried restarting Icinga2 and that did not help.
The API for me, specifically has problems with remove-downtime, which I noticed, got changed in the latest release.
Also the API user has the needed privileges.
Here's my playbook:
```
- hosts: <downtimedhost>
  tasks:
    - name: Removing downtime.
      delegate_to: <icingahost> # Firewall reasons.
      uri:
        url: https://icingahost:correctport/v1/actions/remove-downtime
        url_password: pass # not the actual pass ofcourse
        url_username: username
        method: "POST"
        body: '{"filter": "host.name==\"{{ ansible_nodename }}\"", "pretty": true, "type": "Downtime", "author": "Ansible"}'
        body_format: json
        validate_certs: no
        return_content: yes
        headers:
          Content-Type: "application/json"
          Accept: "application/json"
```
