### ISSUE TITLE
API memory leak with signalilo

### ISSUE THREAD

**Issue by yoshi314** [Icinga/icinga2#8290]
## Describe the bug

I use icinga2 on lxc, and signalilo runs in k8s.

I have installed signalilo as follows : 

checkout https://github.com/appuio/charts/
cd signalilo

edit values.yaml to your liking, e.g

```
config:
  uuid: 9ec06d59-aa0c-4434-b5e2-1aeaf93cd925
  icinga_hostname: kubernetes-dev-cluster
  icinga_url: https://192.168.16.18:5665
  icinga_username: signalilo
  icinga_password: signalilopass
  # icinga_password_secret:
  alertmanager_port: 8888
  alertmanager_bearer_token: alertmanagertoken
  # alertmanager_bearer_token_secret:

```

Define a passive check in icinga2

```
template Service "signalilo-heartbeat" {
	vars.dummy_text = {{
		var service = get_service(macro("$host.name$"), macro("$service.name$"))
		var lastCheck = DateTime(service.last_check).to_string()

		return "Last heartbeat from Signalilo @ " + lastCheck
	}}
}

object Service "heartbeat" {
	import "signalilo-heartbeat"
	display_name = "Heartbeat from signalilo at k8s-dev"
	check_command = "dummy"
	check_interval = 300s
	max_check_attempts = 1
	enable_perfdata = false
	vars.dummy_state = 1
	host_name = "kubernetes-dev-cluster"
}
```

## To Reproduce

1. Configure icinga2 and signalilo
2. Deploy signalilo to your k8s cluster and watch memory usage slowly climb in your icinga2 machine. It takes a while until OOM.

Disabling signalilo makes icinga2 work with no issues.

## Expected behavior

Icinga2 works.

## Screenshots

https://imgur.com/a/zKZlRUm

You can notice the OOM in the flat area of the plot.

## Your Environment

* Version used (`icinga2 --version`):

```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.11.4-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 10 (buster)
  Kernel: Linux
  Kernel version: 4.19.0-8-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 8.3.0
  Build host: runner-ltrjqz9n-project-298-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

```

* Operating System and version: Debian 10
* Enabled features (`icinga2 feature list`):
```
Enabled features: api checker command compatlog graphite ido-mysql livestatus mainlog notification statusdata syslog
```
