### ISSUE TITLE
Process-check-results simultaneus with an Icinga Director deployment are forgetten by Icinga 2

### ISSUE THREAD

**Issue by DamianoChini** [Icinga/icinga2#9365]
## Describe the bug

The Check Results sent via the process-check-result API are forgotten by Icinga 2 if the process-check-result API is called during an Icinga Director deployment. The process-check-result request terminates successfully with 200 status code, but after the deployment Icinga 2 does not have the Check Result set.

## To Reproduce

On a clean Icinga 2 installation execute the script below. 
The script does the following:

1. Triggers the Icinga Director deployment
2. Waits 1 second (empirically this is a good time to wait in order to encounter the race condition)
3. Creates a Host via Icinga 2 API. The `enable_active_checks` property is set to false in order to avoid overwriting the process-check-result sent via API.
4. Sends a process-check-result on the Host just created. 

With a good probability (about 30% of the times) you will reproduce the problem (since it's a race condition I cannot provide a way to reproduce it with a 100% probability). To reproduce the problem execute the script multiple times with different `HOST_NAME`s until you see that the host remains in pending state in the Monitoring of IcingaWeb2.

```
#!/bin/bash

ICINGA_PWD="icinga"
HOST_NAME="h01"

icingacli director config deploy --force

sleep 1

echo "Creating host ${HOST_NAME}"
curl -k -u root:"${ICINGA_PWD}" -H "Accept: application/json" \
-X PUT "https://localhost:5665/v1/objects/hosts/${HOST_NAME}" \
-d '{ "attrs": { "address": "127.0.0.1", "check_command": "hostalive", "enable_active_checks": false}}'

echo -e "\n\nSetting process-check-result on host ${HOST_NAME}"
curl -k -u root:"${ICINGA_PWD}" -H "Accept: application/json" \
 -X POST "https://localhost:5665/v1/actions/process-check-result" \
-d '{ "type": "Host", "host": "'${HOST_NAME}'", "exit_status": 1, "plugin_output": "PING CRITICAL - Packet loss = 100%"}'
```

Now check that the Host is in `PENDING` state in the Monitoring of IcingaWeb 2 (or alternatively check via API that the `last_check_result` of the object is `null` with `curl -k -u root:"${ICINGA_PWD}" -H "Accept: application/json" -X GET "https://localhost:5665/v1/objects/hosts/${HOST_NAME}"` 

Below you see what the Monitoring interface of IcingaWeb2 displays. Notice how sometimes, the state results `PENDING` but the plugin_output contains the string that was sent with the process-check-result (I think that the Check Result is written to the Icinga IDO and then it is wrongly deleted partially from the IDO when the new Icinga 2 instance starts).
![image](https://user-images.githubusercontent.com/49639341/166661825-8d925d3d-aa52-4be5-b32a-b11df61820ab.png)

Status of the host `h03` in Icinga 2:
```
curl -s -k -u root:"${ICINGA_PWD}" -H "Accept: application/json" -X GET "https://localhost:5665/v1/objects/hosts/h03" | jq
{
  "results": [
    {
      "attrs": {
        "__name": "h03",
        "acknowledgement": 0,
        "acknowledgement_expiry": 0,
        "action_url": "",
        "active": true,
        "address": "127.0.0.1",
        "address6": "",
        "check_attempt": 1,
        "check_command": "hostalive",
        "check_interval": 300,
        "check_period": "",
        "check_timeout": null,
        "command_endpoint": "",
        "display_name": "h03",
        "downtime_depth": 0,
        "enable_active_checks": false,
        "enable_event_handler": true,
        "enable_flapping": false,
        "enable_notifications": true,
        "enable_passive_checks": true,
        "enable_perfdata": true,
        "event_command": "",
        "executions": null,
        "flapping": false,
        "flapping_current": 0,
        "flapping_last_change": 0,
        "flapping_threshold": 0,
        "flapping_threshold_high": 30,
        "flapping_threshold_low": 25,
        "force_next_check": false,
        "force_next_notification": false,
        "groups": [],
        "ha_mode": 0,
        "handled": false,
        "icon_image": "",
        "icon_image_alt": "",
        "last_check": -1,
        "last_check_result": null,
        "last_hard_state": 1,
        "last_hard_state_change": 0,
        "last_reachable": true,
        "last_state": 1,
        "last_state_change": 0,
        "last_state_down": 0,
        "last_state_type": 0,
        "last_state_unreachable": 0,
        "last_state_up": 0,
        "max_check_attempts": 3,
        "name": "h03",
        "next_check": 1651658994.476602,
        "notes": "",
        "notes_url": "",
        "original_attributes": null,
        "package": "_api",
        "paused": false,
        "previous_state_change": 0,
        "problem": true,
        "retry_interval": 60,
        "severity": 24,
        "source_location": {
          "first_column": 0,
          "first_line": 1,
          "last_column": 16,
          "last_line": 1,
          "path": "/neteye/shared/icinga2/data/lib/icinga2/api/packages/_api/c2a58281-34f3-4125-b8c7-9d5b31be18a9/conf.d/hosts/h03.conf"
        },
        "state": 1,
        "state_type": 0,
        "templates": [
          "h03"
        ],
        "type": "Host",
        "vars": null,
        "version": 1651658649.193805,
        "volatile": false,
        "zone": "master"
      },
      "joins": {},
      "meta": {},
      "name": "h03",
      "type": "Host"
    }
  ]
}
``` 

icinga_hoststatus of host `h03` in the IDO of Icinga 2:
```
MariaDB [icinga]> select * from icinga_hoststatus where host_object_id = 260\G
*************************** 1. row ***************************
                hoststatus_id: 6
                  instance_id: 1
               host_object_id: 260
           status_update_time: 2022-05-04 10:04:15
                       output: PING CRITICAL - Packet loss = 100%
                  long_output: 
                     perfdata: 
                 check_source: ne423
                current_state: 1
             has_been_checked: 0
          should_be_scheduled: 0
        current_check_attempt: 1
           max_check_attempts: 3
                   last_check: NULL
                   next_check: 2022-05-04 10:04:39
                   check_type: 1
            last_state_change: 2022-05-04 10:04:03
       last_hard_state_change: 2022-05-04 10:04:03
              last_hard_state: 1
                 last_time_up: NULL
               last_time_down: 2022-05-04 10:04:09
        last_time_unreachable: NULL
                   state_type: 0
            last_notification: NULL
            next_notification: NULL
        no_more_notifications: 0
        notifications_enabled: 1
problem_has_been_acknowledged: 0
         acknowledgement_type: 0
  current_notification_number: 0
       passive_checks_enabled: 1
        active_checks_enabled: 0
        event_handler_enabled: 1
       flap_detection_enabled: 0
                  is_flapping: 0
         percent_state_change: 0
                      latency: 0
               execution_time: 0
     scheduled_downtime_depth: 0
   failure_prediction_enabled: 0
     process_performance_data: 1
             obsess_over_host: 0
     modified_host_attributes: 0
          original_attributes: null
                event_handler: NULL
                check_command: hostalive
        normal_check_interval: 5
         retry_check_interval: 1
   check_timeperiod_object_id: 0
                 is_reachable: 1
           endpoint_object_id: 239
1 row in set (0.000 sec)
```

Below you find the complete debug log of Icinga 2 when the problem occurs. You can search for the string `h03` to find when the problem occurred.
[debug.log](https://github.com/Icinga/icinga2/files/8619379/debug.log)

Notice how the process check result for host `h03` arrives after receiving the Director deployment and right before the Application shuts down. After the restart of Icinga 2 the host `h03` is deactivated: `[2022-05-04 10:04:09 +0000] notice/IdoMysqlConnection: Deactivate deleted object name1: 'h03' name2: ''.`

## Expected behavior

I expect that when the process-check-result API returns 200 OK, the corresponding Check Result persists in Icinga 2 even when the process-check-result was sent during an Icinga Director deployment. If Icinga 2 is in a state where it cannot accept process-check-results it should return an error

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): r2.11.9-1
* Operating System and version: Red Hat Enterprise Linux release 8.4 (Ootpa)
* Enabled features (`icinga2 feature list`): api checker debuglog ido-mysql influxdb livestatus mainlog notification
* Icinga Web 2 version and modules (System - About): 2.8.5
* Config validation (`icinga2 daemon -C`): 
* [2022-05-04 09:39:44 +0000] information/cli: Icinga application loader (version: r2.11.9-1)
[2022-05-04 09:39:44 +0000] information/cli: Loading configuration file(s).
[2022-05-04 09:39:44 +0000] information/ConfigItem: Committing config item(s).
[2022-05-04 09:39:44 +0000] information/ApiListener: My API identity: ne423withssh
[2022-05-04 09:39:44 +0000] information/ConfigItem: Instantiated 1 NotificationComponent.
[2022-05-04 09:39:44 +0000] information/ConfigItem: Instantiated 1 LivestatusListener.
[2022-05-04 09:39:44 +0000] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2022-05-04 09:39:44 +0000] information/ConfigItem: Instantiated 1 CheckerComponent.
[2022-05-04 09:39:44 +0000] information/ConfigItem: Instantiated 1 InfluxdbWriter.
[2022-05-04 09:39:44 +0000] information/ConfigItem: Instantiated 244 Services.
[2022-05-04 09:39:44 +0000] information/ConfigItem: Instantiated 3 Zones.
[2022-05-04 09:39:44 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
[2022-05-04 09:39:44 +0000] information/ConfigItem: Instantiated 23 Hosts.
[2022-05-04 09:39:44 +0000] information/ConfigItem: Instantiated 2 NotificationCommands.
[2022-05-04 09:39:44 +0000] information/ConfigItem: Instantiated 1 Endpoint.
[2022-05-04 09:39:44 +0000] information/ConfigItem: Instantiated 2 FileLoggers.
[2022-05-04 09:39:44 +0000] information/ConfigItem: Instantiated 7 ApiUsers.
[2022-05-04 09:39:44 +0000] information/ConfigItem: Instantiated 238 CheckCommands.
[2022-05-04 09:39:44 +0000] information/ConfigItem: Instantiated 1 ApiListener.
[2022-05-04 09:39:44 +0000] information/ScriptGlobal: Dumping variables to file '/neteye/shared/icinga2/data/cache/icinga2/icinga2.vars'
[2022-05-04 09:39:44 +0000] information/cli: Finished validating the configuration file(s).

## Additional context

The problem is affecting us importantly because we have systems where the Icinga Director deployment is triggered many times a day via Director Config Job, and external services send many of process-check-results. This results in many Check Results being completely lost.

A possible explanation for this behaviour is that when Icinga 2 spawns the new reload process (caused by the Director deployment), the old process still accepts API requests. So the new reload process reads the config and starts, then an API request is processed by the old process, then the old process is killed. At this point the new process is not aware of the API request arrived to the old process.
